# report_generator/report_builder.py

import json
from datetime import datetime


def build_markdown_report(incident, ai_output, decision_output, execution_output):

    report = f"""
# Incident Report — {incident['incident_id']}

## 🕒 Timestamp
{incident['timestamp']}

## 🚨 Alarm
{incident['alarm_name']}

## 🖥 Resource
{incident['resource_id']}

---

## 📊 Metrics
- CPU Avg: {incident['metrics']['cpu_utilization_avg']}%
- Memory Avg: {incident['metrics']['memory_utilization_avg']}%
- Latency P95: {incident['metrics']['request_latency_p95']}s

---

## 📜 Recent Logs
"""

    for log in incident.get("recent_logs", [])[:10]:
        report += f"- {log}\n"

    report += f"""

---

## 🤖 AI Root Cause Analysis

**Root Cause:** {ai_output['root_cause']}

**Confidence Score:** {ai_output['confidence_score']}

---

## 🛡 Safety Evaluation

Approved Actions:
"""

    for action in decision_output.get("approved_actions", []):
        report += f"- {action['action']['action_type']}\n"

    report += "\nPending Approval:\n"

    for action in decision_output.get("pending_approval", []):
        report += f"- {action['action']['action_type']}\n"

    report += "\n---\n\n## ⚙️ Execution Results\n"

    for result in execution_output.get("execution_results", []):
        report += f"- {result['action_type']} → {result['status']}\n"

    report += "\n---\n\n## 📌 Generated By\nAegisRCA Automated Incident System\n"

    return report
